### ISSUE TITLE
Update Readme to reflect contents

### ISSUE THREAD

**Issue by lvanfretti** [ALSETLab/Modelica-Drone-3D-FMI#13]
@mpodlaski we should modify the Readme to reflect the contents.
The current description can be used as a "User Guide" which you can put in a different markdown file.
Then, the landing page can be simplified and updated to reflect the different models and resources that we are putting here.

**Comment by dietmarw** [comment]
@lvanfretti @mpodlaski Has this been dealt with in the meantime?

**Comment by lvanfretti** [comment]
@mpodlaski mentioned to me yesterday that the portion of the library will be updated using the user’s guide from the library once we finish with #45

**Comment by dietmarw** [comment]
Fixed in #45
