### ISSUE TITLE
Add fmpy Python scripts, GUI and Jupyter Notebook examples

### ISSUE THREAD

**Issue by lvanfretti** [ALSETLab/Modelica-Drone-3D-FMI#2]
@t-sommer maybe you can help with this?

I don't really understand how to provide inputs from the fmpy GUI, is it possible?

There is a script example, I can use that for a Python script and Jupyter NB example; but don't know how to do it from the GUI.

**Comment by t-sommer** [comment]
In the FMPy GUI just check "Input" on the "Settings" tab and select a CSV that contains the input. Here's an example of an FMU with inputs: https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/win64/Dymola/2017/CoupledClutches

**Comment by lvanfretti** [comment]
Nice to have, but not necessary.
