### ISSUE TITLE
Simulation error 

### ISSUE THREAD

**Issue by showbizas0450** [ALSETLab/Modelica-Drone-3D-FMI#3]
I am running Wolfram System Modeler since I haven't bought Dymola as of now. The software does load the package and the model is globally balanced but during simuation i get the following error
 Error: Equation ramp.y = ramp.offset + (if time < ramp.startTime then 0.0 else if time < ramp.startTime + ramp.duration then (time - ramp.startTime) * ramp.height / ramp.duration else ramp.height) has no unknown variables to solve for.
. If you have any idea what might be causing this error then please inform me. The complete statement is that the error equation has no unknown variable to solve for.

**Comment by mpodlaski** [comment]
Hi this is sort of delayed, but which model are you trying to simulate?

**Comment by showbizas0450** [comment]
Yup some annotations in system modeler aren't present so it took that as
error since it was developed for open modelica .. the problem is fixed now
thanks for replying still .

**Comment by mpodlaski** [comment]
Ok great! I'm glad it's working now.

**Comment by showbizas0450** [comment]
Your simulation really helped me develop my own simulation according to PWM
control for quad . Thanks

**Comment by lvanfretti** [comment]
@showbizas0450 can you share your modified model for SystemModeler? we can include it as an additional version in the repo.
