### ISSUE TITLE
TorqueSensor model is broken

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#38]
`DroneSimulation.Sensors.TorqueSensor` is broken also would be hard to measure torque with just one flange. This model is not used anywhere and should probably be removed. If one needs a torque sensor then `Modelica.Mechanics.Rotational.Sensors.TorqueSensor` can be used instead.

**Comment by mpodlaski** [comment]
Removed component, it was a test file that I missed. It is a duplicate of Modelica.Rotational.Sensors.TorqueSensor

**Comment by dietmarw** [comment]
The file is still present.

**Comment by dietmarw** [comment]
Removed in ae6acf7c6e5a489bccc38c745ae38a5728fca757
