### ISSUE TITLE
Tests package contains broken models

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#39]
in `DroneSimulation.Tests` there are several models that contain broken links. Probably easy to fix if one knows which component should be linked to (and which was probably moved around).

**Comment by mpodlaski** [comment]
Fixed links to the models. Checks without errors now.

**Comment by dietmarw** [comment]
Fixed in 8e6c491f640f46318c6b20d377b5a13aba953f52
