### ISSUE TITLE
Which version of BrushlessDCDrives should it be if at all?

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#40]
Currently, the DroneLibrary depends on the commercial BrushlessDCDrives library which will be shipped as version 1.3.0 (non-backwards compatible with conversion script) in Dymola 2023x Reresh1. Now the current master (at point ae6acf7c6e5a489bccc38c745ae38a5728fca757 at the time of writing) still uses version 1.2.1 (as shipped with Dymola 2023x. 

This means every time somebody with the most recent version of Dymola will, when opening the DroneLibrary experience a warning message that the just opened library needs to get updated. Which really is non-optimal. 

Having looked a bit closer, the only reason for the dependency on the BrushlessDCDrives library is this one model `DroneSimulation.Mechanical.Motor.DCMotor_Averaged_Machine` which is used in two examples. The question now is, how important/useful are those two examples to justify the dependency of a whole commercial library that just provides a very simple model pretty much similar to `DroneSimulation.Electrical.Machines.SimpleMotor_EMF` (because that's all it is internally).

**Comment by mpodlaski** [comment]
I had included the brushlessDC drives models for another one of my projects, but I don't think it is necessary to keep it for this release of the library. I think the only difference between the BrushlessDCDrives model and the SimpleMotor_EMF model is the inclusion of a friction component on the machine's rotor.

I will remove it to limit dependencies on commercial libraries

**Comment by dietmarw** [comment]
@mpodlaski, looks like you removed the packages in 85eb4704138269aa75e186f8273ca63d555cfbb5 but forgot the removal of the annotation itself. Done in https://github.com/ALSETLab/Modelica-Drone-3D-FMI/commit/5868d9319b6c3b9cf622543f44c17021edab91ab
