### ISSUE TITLE
Unit problems with bp

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#41]
Running a check on DroneLibrary will report quite a lot of unit errors. Most of them stem from 

` parameter Modelica.Units.SI.Impulse bp = 2e-2 "Propeller friction force";`

which has the unit `N.s`  but since used in the equation : 

` Jp*der(w)= tout-bp*(w^2);`

needs to have the unit of an inertia, i.e., `kg.m2`.

So how true is it that `bp` is a friction force rather than another type of inertia?

**Comment by mpodlaski** [comment]
bp and ke are both unitless constants, updated to have type `Real` in the model.

(edited by @dietmarw: changed in 5cbf88d2ef4f51f8da6a3061775beb3f732ce5af 

btw if you mention the ticket number in your commit (e.g., "related to #41") then the commit hash will show up automatically here in the time line)

**Comment by dietmarw** [comment]
Unfortunately, that will not help to satisfy the units in 

`Jp*der(w)= tout-bp*(w^2);`

`bp` **needs** to be of unit `kg.m2` (or equivalent).

(setting the type to `Real` will indeed shut up the unit check but just because then Dymola will automatically assign it the matching unit. Not ideal though since now it got the unit of `J.s2.rad-2` (which is a `kg.m2` equivalent if you ignore the `rad` part)

**Comment by dietmarw** [comment]
Or the equation is wrong, which is of course also a possibility (which the unit check kind of points to).

**Comment by mpodlaski** [comment]
Ah ok, bp is used in a lot of the literature as a simplification of a lot of non-varying physical qualities (eg air density). It's so they can reduce the calculation to bp*w^2 without having to worry about further details of the operating environment. I ended up defining my own variable (1a835295f106b7a3e4242ec8f4fa3cce0cc4b470) as a result to fit the units, let me know if it works

**Comment by dietmarw** [comment]
That would work. Just some minor adjustments:
 - Types should start with a capital letter (I'm fixing that now).
 - As long as the type is **only** relevant in that one model then keeping it local is fine. Otherwise one should create a `Types` package to collect them for the library. 

If it is only locally meant then we can close this issue. :-)

**Comment by mpodlaski** [comment]
ok! The only place they will be used is within that model, so it should be ok
