### ISSUE TITLE
Clean up library dependencies

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#42]
Currently, the DroneLibrary states the following dependencies:
- Visualization(version="1.5.1")
  - OK 
- **IdealizedContact(version="0.2.0")**
  -  Only used in some test models, plus the latest version is still based on MSL 3.x.x  and would need conversion and updating and cutting a release upstream
  - it looks like the original developer has become inactive a long time ago.
  - solution: either integrate the components needed from IdealizedContacts in a sublibrary of DroneLibrary (I would probably store those components under `DroneLibrary.IdealizedContacts` keeping the same internal hierarchy **or** remove the example models if they are found as not that important
- **ModelicaServices(version="4.0.0")**
  - This library should normally not be used directly by the user (hence it is also not visible by default in Dymola). Currently, the DroneLibrary uses: 
    - `ModelicaServices.ExternalReferences.loadResource` 
   but why not use the proper (user-facing) function:
    - `Modelica.Utilities.Files.loadResource` instead?
- Modelica(version="4.0.0")
  - OK  
- **VeSyMA(version="2023.1")** 
  - I can't find any usage of VeSyMA classes in DroneLibrary itself, other than that this is mentioned in the uses annotation and the README
  - should be removed
- **Claytex(version="2023.1")**
  - same as for VeSyMA
  - should be removed 
- **Battery(version="2.5.0")**
  - same as for VeSyMA
  - should be removed 
- **Modelon(version="4.1")**
  - There are several mentions of Modelon but many packages, though present on the file system do not get loaded by Dymola since they are not listed in the `package.order` file. This needs to get fixed.
 
Mind it could well be that the Visualisation library depends on VeSyMa or Claytex (not sure since I don't have access to that one) but this does not really matter for DroneLibrary since *they* will then state there dependencies to the tool.

**Comment by mpodlaski** [comment]
> - IdealizedContact(version="0.2.0")
> Only used in some test models, plus the latest version is still based on MSL 3.x.x and would need conversion and updating and cutting a release upstream 

**ok, I think they can be removed then.** (done in 779451e7177fcb135176018038d69845b2672a17)
There is another example in the dronecollision package that uses the models with a payload attached to them, so only one model is removed

> - ModelicaServices(version="4.0.0")

removed reference

> This library should normally not be used directly by the user (hence it is also not visible by default in Dymola). Currently, the DroneLibrary uses:
> - ModelicaServices.ExternalReferences.loadResource but why not use the proper (user-facing) function: >Modelica.Utilities.Files.loadResource instead?

where does this get updated?

> - Modelica(version="4.0.0")

 OK

> - VeSyMA(version="2023.1")

removed
> - Claytex(version="2023.1")

removed

> - Battery(version="2.5.0")

removed
> - Modelon(version="4.1")
> There are several mentions of Modelon but many packages, though present on the file system do not get loaded by Dymola since they are not listed in the package.order file. This needs to get fixed.

**Comment by dietmarw** [comment]
Looks like the uses annotations were not updated. So I will do that now. 
As for the not loaded packages, I've now updated the `package.order` files so they appear again. Please have a look if those packages are still relevant or should have been removed anyway since they are old copies.

The packages in question are:
 - `DroneSimulation.Electrical.Sources.FuelCell`
 - `DroneSimulation.Examples.PowerSystem`
 - `DroneSimulation.Examples.Visualization_VR`

Now some of the Modelon referenced modes are not using Modelon but are simply instances (copies) of models from the Modelon lib. In that case, one should rather use the original model from the Modelon lib instead of "copying" them. (see `DroneSimulation.Electrical.Sources.FuelCell.FuelCell`) as an example.

As for the `loadResouce` function, when you do a text search in the Modelica code you can find it. I've updated it to the MSL function now. But best if you can check that the stl files still get loaded correctly.

**Comment by dietmarw** [comment]
When updating the README, I notice that it states that 
> The full version of the [DLR Visualization](https://visualization.ltx.de/) library is required to run any of the models using VR in the DroneSimulation.Visualization package.

Now this would actually be excellent but this is not quite the case since some Visualization dependent models made their way to other packages outside `Visualization`. It would be great if those can be put under `Visualization` since that makes checking much easier.

**Comment by mpodlaski** [comment]
> 

Ok, I've removed the files in question. 

for the visualization, should I add the blade, chassis, etc components dependent on the visualization library in the examples folder? They are all denoted with _visualization in their respective packages.

**Comment by dietmarw** [comment]
For checking purposes, it makes it easier if **everything** that depends on the Visualization library is located under the Visualization subpackage. That way one can simply remove that package (due to lack of license) to check the whole rest of the library and don't have to parse through which error messages are related to the missing Visualization lib and which are "real".

**Comment by dietmarw** [comment]
For checking purposes, it makes it easier if **everything** that depends on the Visualization library is located under the Visualization subpackage. That way one can simply remove that package (due to lack of license) to check the whole rest of the library and don't have to parse through which error messages are related to the missing Visualization lib and which are "real".

**Comment by dietmarw** [comment]
Done for now.
