### ISSUE TITLE
Rename package to DroneLibrary

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#43]
The name "DroneSimulation" is not quite optimal. I think calling it "DroneLibrary" or maybe just "DroneLib" might be much more suitable. 
What do you think?

**Comment by mpodlaski** [comment]
That works with me!

**Comment by dietmarw** [comment]
DroneLib it is then.

**Comment by mpodlaski** [comment]
I renamed it DroneLibrary, let me know if it works on your end before I delete DroneSimulation

**Comment by dietmarw** [comment]
The name is OK by me but I need to revert your change since the way you did it the history is lost. Git is aware if there are renames but simply adding a duplicate that duplicate will have no history whatsoever.

**Comment by dietmarw** [comment]
That change will take some more time since I'm travelling during the next week. Not sure if I will be able to push then.

**Comment by mpodlaski** [comment]
> The name is OK by me but I need to revert your change since the way you did it the history is lost. Git is aware if there are renames but simply adding a duplicate that duplicate will have no history whatsoever.

ok, in Dymola I am changing it through renaming it and then it forces me to save a new directory. Does it need to be renamed manually?

**Comment by dietmarw** [comment]
Dymola does only half the job. The trick is to then also remove the old directory before creating a commit so that git recognises the rename. Anyway, I managed to fix this now but had to do a "force push". This means you can not simply pull the updates now but have to do a:
```
git fetch --all
git reset --hard origin/master
```
replace "origin" with the name of what you called your ALSETLab remote (e.g., in my case I called it "ALSETLab" instead of "origin")

**Comment by dietmarw** [comment]
Done in 1689681685bfaebfcf7085ec8e8e33f35199c49c
