### ISSUE TITLE
Continuous Integration 

### ISSUE THREAD

**Issue by marcelofcastro** [ALSETLab/Modelica-Drone-3D-FMI#8]
I think it is a good idea to set up some continuous integration for this repository. At least some syntax checking.

**Comment by lvanfretti** [comment]
@marcelofcastro I guess @mpodlaski can do this if you help her.
@mpodlaski this would be useful to explain the way Version Control and Continious Integration could helpmanage versions of the model for the NASA project, so we could use this to illustrate.
